name: Python Pytest CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'

      - name: Install dependencies
        run: |
          # python -m pip install --upgrade pip
          pip install pytest

      - name: Run pytest
<<<<<<< HEAD
        run: pytest test_main.py
=======
        run: |
          pytest

>>>>>>> 9f64ccf2efceaf6bc466694c9d4b9d1d95f53131
